# Transpose Sales Data
Reorganize sales data, where each row represents a product and each column represents a month. Transposing the matrix allows better comparison of sales across different months for each product.

### Implement the Function

In [5]:
import numpy as np

def transpose_sales_data(sales_matrix):
    sales_matrix = np.array(sales_matrix)
    res = sales_matrix.T
    return res

sales_matrix = [
    [200, 180, 220],
    [150, 170, 160],
    [300, 320, 310]
]

print(transpose_sales_data(sales_matrix))


[[200 150 300]
 [180 170 320]
 [220 160 310]]


### Run the Test

In [7]:
import numpy as np

def transpose_sales_data(sales_matrix):
    sales_matrix = np.array(sales_matrix)
    return sales_matrix.T

sales_matrix = [
    [200, 180, 220],
    [150, 170, 160],
    [300, 320, 310]
]

expected_output = np.array([
    [200, 150, 300],
    [180, 170, 320],
    [220, 160, 310]
])

try:
    output = transpose_sales_data(sales_matrix)
    assert np.array_equal(output, expected_output), f"Expected {expected_output}, but got {output}"
    print('✅ Test Passed: Transpose function works correctly.')
except Exception as e:
    print(f'❌ Test Failed: {e}')


✅ Test Passed: Transpose function works correctly.
